export class ApiError extends Error {
  constructor(
    public code: string,
    message?: string,
    public details?: unknown,
    public redirectUrl?: string,
  ) {
    super(`${code}: ${message}`);
    this.name = 'ApiError';
  }
}

export const ErrorCodes = {
  SESSION_INVALID: 'SESSION_INVALID',
  REQUEST_FAILED: 'REQUEST_FAILED',
  RESPONSE_INVALID_CONTENT_TYPE: 'RESPONSE_INVALID_CONTENT_TYPE',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  INVALID_RESET_CODE: 'INVALID_RESET_CODE',
  INVALID_RESET_TOKEN: 'INVALID_RESET_TOKEN',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  UNAUTHORIZED: 'UNAUTHORIZED',
  INVALID_REQUEST: 'INVALID_REQUEST',
  UNSUPPORTED_FILE_TYPE: 'UNSUPPORTED_FILE_TYPE',
  FILE_SIZE_EXCEEDED: 'FILE_SIZE_EXCEEDED',
  FILE_NOT_FOUND: 'FILE_NOT_FOUND',
  FILE_IN_USE: 'FILE_IN_USE',
  FORBIDDEN: 'FORBIDDEN',
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  INVALID_OTP: 'INVALID_OTP',
};
